baseURL = "https://jiangdongxu.online"
languageCode = "zh-cn"
title = "蒋东旭"

[params]
    subtitle = "Financial Engineering @ DUFE"
    description = "Competitions, Business Activities, Learning, or Coffee Talk — Contact Me!"
    github = "aB-iJ"
    qq = "268431892"
    wechat = "jiangdongxu0755"
    email = "268431892@qq.com"
    hasCJKLanguage = true

[markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false

[markup.goldmark.renderer]
    unsafe = true
